-- Insertion des valeurs dans la table

INSERT INTO accroche(accroche, poids) VALUES
	('BREAKING', 10),
	('BREAKING NEWS', 10),
	('FLASH', 10),
	('FLASH NEWS', 10),
	('DIRECT', 10),
	('EXCLUSIVITÉ', 8),
	('ALERTE INFO -', 15),
	('SCOOP', 5),
	('C’est officiel :', 5);
	
INSERT INTO structure(structure, poids) VALUES
	('{emoji} {accroche} {sujet.nom} {info.action}.', 30),
	('{emoji} {accroche} {sujet.nom} {info.action} {rand({date},{lieu})}.', 10),
	('{emoji} {accroche} {sujet.nom} {info.action} {date} {lieu}.', 10),
	('{emoji} {accroche} {sujet.nom} {info.action} {info.circo}.', 10),
	('{emoji} {accroche} {sujet.nom} {info.action} {rand({date},{lieu})} {info.circo}.', 10),
	('{emoji} {accroche} {sujet.nom} {info.action} {date} {lieu} {info.circo}.', 10),
	('{emoji} {accroche.sans(:)} {sujet.nom} : {sujet.surnom} {info.action}.', 30),
	('{emoji} {accroche.sans(:)} {sujet.nom} : {sujet.surnom} {info.action} {rand({date},{lieu})}.', 10),
	('{emoji} {accroche.sans(:)} {sujet.nom} : {sujet.surnom} {info.action} {date} {lieu}.', 10),
	('{emoji} {accroche.sans(:)} {sujet.nom} : {sujet.surnom} {info.action} {info.circo}.', 10),
	('{emoji} {accroche.sans(:)} {sujet.nom} : {sujet.surnom} {info.action} {rand({date},{lieu})} {info.circo}.', 10),
	('{emoji} {accroche.sans(:)} {sujet.nom} : {sujet.surnom} {info.action} {date} {lieu} {info.circo}.', 10);

INSERT INTO pers(nom_colle, genre, poids) VALUES
	('Norman', 'M', 10),
	('{rand(,Emmanuel)}Macron', 'M', 10),
	('Yoshi', 'M', 10),
	('Kemar', 'M', 10),
	('Mario', 'M', 10),
	('{rand(JL,)}Mélenchon', 'M', 10),
	('{rand(Donald,)}Trump', 'M', 10),
	('KimJongUn', 'M', 10),
	('Morsay', 'M', 10),
	('Cortex', 'M', 10),
	('Jul', 'M', 10),
	('Cyprien', 'M', 10),
	('MisterV', 'M', 10),
	('Squeezie', 'M', 10),
	('UnIndividu', 'M', 10),
	('UnLycéen', 'M', 10),
	('Damso', 'M', 10),
	('Luis Fonsi', 'M', 10),
	('ElonMusk', 'M', 10),
	('Ramzy', 'M', 10),
	('Rayman', 'M', 10),
	('{rand(,François)}Fillon', 'M', 10),
	('{rand(,Nicolas)}Sarkozy', 'M', 10),
	('LinspecteurDesImpôts', 'M', 10),
	('LinspecteurDesComptesPublics', 'M', 10),
	('{rand(,Mark)}Zuckerberg', 'M', 10),
	('JeffBezos', 'M', 10),
	('MohamedHenni', 'M', 10),
	('FrançoisHollande', 'M', 10),
	('Luigi', 'M', 10),
	('Wario', 'M', 10),
	('Herobrine', 'M', 10),
	('Link', 'M', 10),
	('{rand(,Barack)}Obama', 'M', 10),
	('Waluigi', 'M', 10),
	('Rilès', 'M', 10),
	('Zidane', 'M', 10),
	('Fouiny', 'M', 10),
	('Usul', 'M', 10),
	('{rand(Alain,)}Juppé', 'M', 10),
	('XavierNiel', 'M', 10),
	('Sans', 'M', 10),
	('Yoda', 'M', 10),
	('ChristopheBarbier', 'M', 10),
	('PascalPraud', 'M', 10),
	('ÉricBrunet', 'M', 10),
	('{rand(,Raphaël)}Enthoven', 'M', 10),
	('ÉdouardPhilippe', 'M', 10),
	('PhilippeMartinez', 'M', 10),
	('PierreMénès', 'M', 10),
	('Banksy', 'M', 10),
	('PapeFrançois', 'M', 10),
	('Poutine', 'M', 10),
	('Benalla', 'M', 10),
	('{rand(Patrick,)}Balkany', 'M', 10),
	('GérardColomb', 'M', 10),
	('UnPolicier', 'M', 10),
	('LePréfetDePolice', 'M', 10),
	('TheKairi78', 'M', 10),
	('Booba', 'M', 10),
	('Kaaris', 'M', 10),
	('HugoClément', 'M', 10),
	('UnChien', 'M', 10),
	('UnChat', 'M', 10),
	('NicolasHulot', 'M', 10),
	('Nemo', 'M', 10),
	('PierreRabhi', 'M', 10),
	('StéphaneBern', 'M', 10),
	('{rand(Éric,)}Zemmour', 'M', 10),
	('LaurentRuquier', 'M', 10),
	('{rand(Michel,)}Drucker', 'M', 10),
	('GoogleAssistant', 'M', 10),
	('Siri', 'M', 10),
	('{rand(XavierDupontDeLigonnès,XDDL)}', 'M', 10),
	('Bowser', 'M', 10),
	('TomNook', 'M', 10),
	('JeanMarieLePen', 'M', 5),
	('{rand(Manuel,)}Valls', 'M', 10),
	('{rand(Cyril,)}Hanouna', 'M', 10),
	('LilPump', 'M', 10),
	('KanyeWest', 'M', 10),
	('BillGates', 'M', 10),
	('BernardArnault', 'M', 10),
	('{rand(Jacques,)}Chirac', 'M', 10),
	('Giscard', 'M', 10),
	('{rand(Christophe,)}Castaner', 'M', 10),
	('AlainChabat', 'M', 10),
	('AlexandreAstier', 'M', 10),
	('AlainDeBitssbailledrey', 'M', 2),
	('ThierryPelouse', 'M', 2),
	('AdolfMussolin', 'M', 2),
	('GaetanLeSinge', 'M', 2),
	('PacoLopez', 'M', 2),
	('Gims', 'M', 10),
	('KevAdams', 'M', 10),
	('LeProcureur', 'M', 10),
	('{rand(JoueurDuGrenier,JDG)}', 'M', 10),
	('DavidLafarge', 'M', 10),
	('CédricVillani', 'M', 10),
	('Gouvernement', 'M', 10),
	('{rand(François,)}Asselineau', 'M', 10),
	('LoràntDeutsch', 'M', 10),
	('SteveDeMinecraft', 'M', 10),
	('{rand(Laurent,)}Wauquiez', 'M', 10),
	('AlexisCorbière', 'M', 10),
	('EdwyPlenel', 'M', 10),
	('JeanMichelAulas', 'M', 10),
	('DidierDeschamps', 'M', 10),
	('{rand(Bruno,)}Genesio', 'M', 10),
	('{rand(Olivier,)}Giroud', 'M', 10),
	('{rand(Florian,)}Thauvin', 'M', 10),
	('{rand(Blaise,)}Matuidi', 'M', 10),
	('BillDuBigdil', 'M', 5),
	('PabloIglesias', 'M', 5),
	('GiletJaune', 'M', 10),
	('Thanos', 'M', 10),
	('InventeurDuDab', 'M', 10),
	('{inventeur_dab.nom_colle}', 'M', 10),
	('AdministrateurDeLaPageGiletsJaunes', 'M', 10),
	('BernieSanders', 'M', 10),
	('JeanPierrePernault', 'M', 10),
	('FlorianOnAir', 'M', 5),
	('TiboInShape', 'M', 10),
	('AlainSoral', 'M', 5),
	('Dieudonné', 'M', 5),
	('PhilippePoutou', 'M', 10),
	('OlivierBesancenot', 'M', 10),
	('KarimDebbache', 'M', 10),
	('KarimBenzema', 'M', 10),
	('XiJinping', 'M', 10),
	('Journaliste', 'M', 10),
	('Assassin{victime.nom_colle(De)}', 'M', 10),
	('Victime{assassin.nom_colle(De)}', 'M', 10),
	('Avocat{client.nom_colle(De)}', 'M', 10),
	('Agriculteur', 'M', 10),
	('BlackBloc', 'M', 10),
	('CarlosGhosn', 'M', 5),
	('PatrickSébastien', 'M', 10),
	('JulienLepers', 'M', 10),
	('YannBarthès', 'M', 10),
	('Kirby', 'M', 10),
	('{rand(Nicolas,)}DupontAignan', 'M', 10),
	('QuelquUn', 'M', 10),
	('Personne', 'M', 10),
	('Fan{idole.nom_colle(De)}', 'M', 10),
	('StéphanePlaza', 'M', 10),
	('{rand(JeanClaudeVanDamme,JCVD)}', 'M', 10),
	('IbraTV', 'M', 10),
	('{rand(Antoine,)}Griezmann', 'M', 10),
	('Lacrim', 'M', 10),
	('Indépendantiste', 'M', 10),
	('DamienSaez', 'M', 10),
	('{rand(Jérôme,)}Cahuzac', 'M', 10),
	('{rand(François,)}Ruffin', 'M', 10),
	('{rand(GeorgeW,)}Bush', 'M', 10),
	('ÉricJudor', 'M', 10),
	('BenjaminNetanyahu', 'M', 10),
	('FilsCaché{parent.nom_colle(De)}', 'M', 10),
	('Terroriste', 'M', 5),
	('JulienCoupat', 'M', 10),
	('Rohff', 'M', 10),
	('Bouteflika', 'M', 10),
	('Garfield', 'M', 10),
	('JeanPierreFoucault', 'M', 5),
	('DavidGuetta', 'M', 5),
	('Jack', 'M', 10),
	('BenoîtHamon', 'M', 10),
	('Militant{parti_militant.sigle}', 'M', 10),
	('{rand(Jeremy,)}Corbyn', 'M', 10),
	('CRS', 'M', 10),
	('{rand(Gérard,)}Depardieu', 'M', 10),
	('Zizek', 'M', 10),
	('PewDiePie', 'M', 10),
	('Internet', 'M', 10),
	('Plantu', 'M', 10),
	('YannMoix', 'M', 10),
	('Prantu', 'M', 10),
	('AlainTeub', 'M', 2),
	('BakariKonté', 'M', 2),
	('DimitriCrackers', 'M', 2),
	('JayZ', 'M', 5),
	('Maduro', 'M', 5),
	('{rand(Éric,)}DupontMoretti', 'M', 10),
	('UnHomme', 'M', 10),
	('Reggie{rand(Fils-Aimé,)}', 'M', 10),
	('AntoineDaniel', 'M', 10),
	('Drake', 'M', 10),
	('ElPueblo', 'M', 10),
	('GadElmaleh', 'M', 10),
	('PhilippeEtchebest', 'M', 10),
	('GordonRamsay', 'M', 10),
	('ThomasCyrix', 'M', 5),
	('{rand(François,)}DeRugy', 'M', 10),
	('BorisJohnson', 'M', 10),
	('Maire{ville_maire.nom_colle(De)}', 'M', 10),
	('FranckyVincent', 'M', 10),
	('6ix9ine', 'M', 10),
	('JeanMarieBigard', 'M', 10),
	('LaurentAlexandre', 'M', 10),
	('LaFilleQuiLitCeci', 'F', 10),
	('BrigitteMacron', 'F', 10),
	('Bowsette', 'F', 10),
	('Peach', 'F', 10),
	('MarieDAnimalCrossing', 'F', 10),
	('MarineLePen', 'F', 10),
	('Alexa', 'F', 10),
	('HillaryClinton', 'F', 10),
	('AdministratriceDeLaPageGiletsJaunes', 'F', 10),
	('Poule', 'F', 10),
	('Natoo', 'F', 10),
	('MylèneFarmer', 'F', 10),
	('Arielle Dombasle', 'F', 10),
	('LaurenceBoccolini', 'F', 5),
	('ValérieDamidot', 'F', 5),
	('AuroreBergé', 'F', 10),
	('NicoleBelloubet', 'F', 10),
	('ChristineBoutin', 'F', 5),
	('FrigideBarjot', 'F', 5),
	('TheresaMay', 'F', 10),
	('AyaNakamura', 'F', 10),
	('{rand(Angela,)}Merkel', 'F', 10),
	('IsabelleBalkany', 'F', 10),
	('Journaliste{ignore(F)}', 'F', 10),
	('Nabilla', 'F', 10),
	('AnneHidalgo', 'F', 10),
	('MelaniaTrump', 'F', 10),
	('ÉlisabethII', 'F', 10),
	('Agricultrice', 'F', 10),
	('Gendarme', 'F', 10),
	('ÉliseLucet', 'F', 10),
	('EugénieBastié', 'F', 5),
	('ChristineAndTheQueens', 'F', 10),
	('{rand(JK,)}Rowling', 'F', 10),
	('BrigitteBardot', 'F', 10),
	('SolangeTeParle', 'F', 5),
	('EnjoyPhoenix', 'F', 10),
	('AzealiaBanks', 'F', 3),
	('Militante{parti_militante.sigle}', 'F', 10),
	('KimKardashian', 'F', 10),
	('MarlèneSchiappa', 'F', 10),
	('CristinaCordula', 'F', 3),
	('ValériePécresse', 'F', 10),
	('Beyoncé', 'F', 10),
	('NickiMinaj', 'F', 10),
	('Maire{ville_maire.nom_colle(De)}{ignore(F)}', 'F', 10),
	('GretaThunberg', 'F', 10),
	('FlashNewsBot', 'F', 10);

INSERT INTO nom_pers(id_pers, nom) VALUES
	((SELECT id FROM pers WHERE nom_colle = 'Norman'), 'Norman'),
	((SELECT id FROM pers WHERE nom_colle = 'Norman'), '#Norman'),
	((SELECT id FROM pers WHERE nom_colle = 'Norman'), 'Norman Thavaud'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(,Emmanuel)}Macron'), 'Emmanuel Macron'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(,Emmanuel)}Macron'), 'E. #Macron'),
	((SELECT id FROM pers WHERE nom_colle = 'Yoshi'), 'Yoshi'),
	((SELECT id FROM pers WHERE nom_colle = 'Mario'), 'Mario'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(JL,)}Mélenchon'), 'Jean-Luc Mélenchon'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(JL,)}Mélenchon'), 'J.-L. #Mélenchon'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Donald,)}Trump'), 'Donald Trump'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Donald,)}Trump'), 'D. #Trump'),
	((SELECT id FROM pers WHERE nom_colle = 'KimJongUn'), 'Kim Jong-Un'),
	((SELECT id FROM pers WHERE nom_colle = 'Morsay'), 'Morsay'),
	((SELECT id FROM pers WHERE nom_colle = 'Cortex'), 'Cortex'),
	((SELECT id FROM pers WHERE nom_colle = 'Jul'), 'Jul'),
	((SELECT id FROM pers WHERE nom_colle = 'Cyprien'), 'Cyprien'),
	((SELECT id FROM pers WHERE nom_colle = 'Cyprien'), 'Cyprien Iov'),
	((SELECT id FROM pers WHERE nom_colle = 'Cyprien'), '#Cyprien'),
	((SELECT id FROM pers WHERE nom_colle = 'MisterV'), 'Mister V'),
	((SELECT id FROM pers WHERE nom_colle = 'MisterV'), 'Yvick Letexier'),
	((SELECT id FROM pers WHERE nom_colle = 'Kemar'), 'Kemar'),
	((SELECT id FROM pers WHERE nom_colle = 'Kemar'), 'Kémar'),
	((SELECT id FROM pers WHERE nom_colle = 'Kemar'), 'Marc Jarousseau'),
	((SELECT id FROM pers WHERE nom_colle = 'Squeezie'), 'Squeezie'),
	((SELECT id FROM pers WHERE nom_colle = 'UnIndividu'), 'un individu'),
	((SELECT id FROM pers WHERE nom_colle = 'UnLycéen'), 'un lycéen'),
	((SELECT id FROM pers WHERE nom_colle = 'Damso'), 'Damso'),
	((SELECT id FROM pers WHERE nom_colle = 'Luis Fonsi'), 'Luis Fonsi'),
	((SELECT id FROM pers WHERE nom_colle = 'ElonMusk'), 'Elon Musk'),
	((SELECT id FROM pers WHERE nom_colle = 'Ramzy'), 'Ramzy'),
	((SELECT id FROM pers WHERE nom_colle = 'Ramzy'), 'Ramzy Bédia'),
	((SELECT id FROM pers WHERE nom_colle = 'Rayman'), 'Rayman'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(,François)}Fillon'), 'François Fillon'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(,François)}Fillon'), 'F. #Fillon'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(,Nicolas)}Sarkozy'), 'Nicolas Sarkozy'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(,Nicolas)}Sarkozy'), 'N. #Sarkozy'),
	((SELECT id FROM pers WHERE nom_colle = 'LinspecteurDesImpôts'), 'l’inspecteur des impôts'),
	((SELECT id FROM pers WHERE nom_colle = 'LinspecteurDesComptesPublics'), 'l’inspecteur des comptes publics'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(,Mark)}Zuckerberg'), 'Mark Zuckerberg'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(,Mark)}Zuckerberg'), 'M. #Zuckerberg'),
	((SELECT id FROM pers WHERE nom_colle = 'JeffBezos'), 'Jeff Bezos'),
	((SELECT id FROM pers WHERE nom_colle = 'JeffBezos'), 'J. #Bezos'),
	((SELECT id FROM pers WHERE nom_colle = 'MohamedHenni'), 'Mohamed Henni'),
	((SELECT id FROM pers WHERE nom_colle = 'FrançoisHollande'), 'François Hollande'),
	((SELECT id FROM pers WHERE nom_colle = 'FrançoisHollande'), 'F. #Hollande'),
	((SELECT id FROM pers WHERE nom_colle = 'Luigi'), 'Luigi'),
	((SELECT id FROM pers WHERE nom_colle = 'Wario'), 'Wario'),
	((SELECT id FROM pers WHERE nom_colle = 'Waluigi'), 'Waluigi'),
	((SELECT id FROM pers WHERE nom_colle = 'Rilès'), 'Rilès'),
	((SELECT id FROM pers WHERE nom_colle = 'Herobrine'), 'Herobrine'),
	((SELECT id FROM pers WHERE nom_colle = 'Link'), 'Link'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(,Barack)}Obama'), 'Barack Obama'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(,Barack)}Obama'), 'B. #Obama'),
	((SELECT id FROM pers WHERE nom_colle = 'Zidane'), 'Zinédine Zidane'),
	((SELECT id FROM pers WHERE nom_colle = 'Zidane'), 'Zidane'),
	((SELECT id FROM pers WHERE nom_colle = 'Zidane'), 'Z. #Zidane'),
	((SELECT id FROM pers WHERE nom_colle = 'Fouiny'), 'La Fouine'),
	((SELECT id FROM pers WHERE nom_colle = 'Usul'), 'Usul'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Alain,)}Juppé'), 'Alain Juppé'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Alain,)}Juppé'), 'A. #Juppé'),
	((SELECT id FROM pers WHERE nom_colle = 'XavierNiel'), 'Xavier Niel'),
	((SELECT id FROM pers WHERE nom_colle = 'XavierNiel'), 'X. #Niel'),
	((SELECT id FROM pers WHERE nom_colle = 'Sans'), 'Sans'),
	((SELECT id FROM pers WHERE nom_colle = 'Sans'), 'Sans Undertale'),
	((SELECT id FROM pers WHERE nom_colle = 'Yoda'), 'Yoda'),
	((SELECT id FROM pers WHERE nom_colle = 'Yoda'), 'Maître Yoda'),
	((SELECT id FROM pers WHERE nom_colle = 'ChristopheBarbier'), 'Christophe Barbier'),
	((SELECT id FROM pers WHERE nom_colle = 'PascalPraud'), 'Pascal Praud'),
	((SELECT id FROM pers WHERE nom_colle = 'ÉricBrunet'), 'Éric Brunet'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(,Raphaël)}Enthoven'), 'Raphaël Enthoven'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(,Raphaël)}Enthoven'), 'R. #Enthoven'),
	((SELECT id FROM pers WHERE nom_colle = 'ÉdouardPhilippe'), 'Édouard Philippe'),
	((SELECT id FROM pers WHERE nom_colle = 'ÉdouardPhilippe'), 'E. #Philippe'),
	((SELECT id FROM pers WHERE nom_colle = 'PhilippeMartinez'), 'Philippe Martinez'),
	((SELECT id FROM pers WHERE nom_colle = 'PhilippeMartinez'), 'P. #Martinez'),
	((SELECT id FROM pers WHERE nom_colle = 'PierreMénès'), 'PierreMénès'),
	((SELECT id FROM pers WHERE nom_colle = 'PierreMénès'), 'P. #Ménès'),
	((SELECT id FROM pers WHERE nom_colle = 'Banksy'), 'Banksy'),
	((SELECT id FROM pers WHERE nom_colle = 'Banksy'), '#Banksy'),
	((SELECT id FROM pers WHERE nom_colle = 'PapeFrançois'), 'le Pape'),
	((SELECT id FROM pers WHERE nom_colle = 'PapeFrançois'), 'le Pape François'),
	((SELECT id FROM pers WHERE nom_colle = 'Poutine'), 'Vladimir Poutine'),
	((SELECT id FROM pers WHERE nom_colle = 'Poutine'), 'Poutine'),
	((SELECT id FROM pers WHERE nom_colle = 'Poutine'), 'V. #Poutine'),
	((SELECT id FROM pers WHERE nom_colle = 'Benalla'), 'Alexandre Benalla'),
	((SELECT id FROM pers WHERE nom_colle = 'Benalla'), 'A. #Benalla'),
	((SELECT id FROM pers WHERE nom_colle = 'Benalla'), 'Benalla'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Patrick,)}Balkany'), 'Patrick Balkany'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Patrick,)}Balkany'), 'P. #Balkany'),
	((SELECT id FROM pers WHERE nom_colle = 'GérardColomb'), 'Gérard Colomb'),
	((SELECT id FROM pers WHERE nom_colle = 'GérardColomb'), 'G. #Colomb'),
	((SELECT id FROM pers WHERE nom_colle = 'UnPolicier'), 'un policier'),
	((SELECT id FROM pers WHERE nom_colle = 'LePréfetDePolice'), 'le préfet de police'),
	((SELECT id FROM pers WHERE nom_colle = 'LePréfetDePolice'), 'le préfet {ville_prefet=ville}{ville_prefet.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'LePréfetDePolice'), 'le préfet {ville_prefet=ville}{ville_prefet.nom(de)} ({ville_prefet.departement})'),
	((SELECT id FROM pers WHERE nom_colle = 'TheKairi78'), 'TheKairi78'),
	((SELECT id FROM pers WHERE nom_colle = 'Booba'), 'Booba'),
	((SELECT id FROM pers WHERE nom_colle = 'Kaaris'), 'Kaaris'),
	((SELECT id FROM pers WHERE nom_colle = 'HugoClément'), 'Hugo Clément'),
	((SELECT id FROM pers WHERE nom_colle = 'UnChien'), 'un chien'),
	((SELECT id FROM pers WHERE nom_colle = 'UnChat'), 'un chat'),
	((SELECT id FROM pers WHERE nom_colle = 'NicolasHulot'), 'Nicolas Hulot'),
	((SELECT id FROM pers WHERE nom_colle = 'NicolasHulot'), 'N. #Hulot'),
	((SELECT id FROM pers WHERE nom_colle = 'Nemo'), 'le chien Nemo'),
	((SELECT id FROM pers WHERE nom_colle = 'PierreRabhi'), 'Pierre Rabhi'),
	((SELECT id FROM pers WHERE nom_colle = 'StéphaneBern'), 'Stéphane Bern'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Éric,)}Zemmour'), 'Éric Zemmour'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Éric,)}Zemmour'), 'E. #Zemmour'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Éric,)}Zemmour'), 'Zemmour'),
	((SELECT id FROM pers WHERE nom_colle = 'LaurentRuquier'), 'Laurent Ruquier'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Michel,)}Drucker'), 'Michel Drucker'),
	((SELECT id FROM pers WHERE nom_colle = 'GoogleAssistant'), 'Google Assistant'),
	((SELECT id FROM pers WHERE nom_colle = 'GoogleAssistant'), 'le Google Assistant'),
	((SELECT id FROM pers WHERE nom_colle = 'Siri'), 'Siri'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(XavierDupontDeLigonnès,XDDL)}'), 'Xavier Dupont de Ligonnès'),
	((SELECT id FROM pers WHERE nom_colle = 'Bowser'), 'Bowser'),
	((SELECT id FROM pers WHERE nom_colle = 'TomNook'), 'Tom Nook'),
	((SELECT id FROM pers WHERE nom_colle = 'JeanMarieLePen'), 'Jean-Marie Le Pen'),
	((SELECT id FROM pers WHERE nom_colle = 'JeanMarieLePen'), 'J.-M. #LePen'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Manuel,)}Valls'), 'Manuel Valls'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Manuel,)}Valls'), 'M. #Valls'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Cyril,)}Hanouna'), 'Cyril Hanouna'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Cyril,)}Hanouna'), 'C. #Hanouna'),
	((SELECT id FROM pers WHERE nom_colle = 'LilPump'), 'Lil Pump'),
	((SELECT id FROM pers WHERE nom_colle = 'KanyeWest'), 'Kanye West'),
	((SELECT id FROM pers WHERE nom_colle = 'BillGates'), 'Bill Gates'),
	((SELECT id FROM pers WHERE nom_colle = 'BernardArnault'), 'Bernard Arnault'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Jacques,)}Chirac'), 'Jacques Chirac'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Jacques,)}Chirac'), 'J. #Chirac'),
	((SELECT id FROM pers WHERE nom_colle = 'Giscard'), 'Valéry Giscard d’Estaing'),
	((SELECT id FROM pers WHERE nom_colle = 'Giscard'), 'V. #Giscard d’Estaing'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Christophe,)}Castaner'), 'Christophe Castaner'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Christophe,)}Castaner'), 'C. #Castaner'),
	((SELECT id FROM pers WHERE nom_colle = 'AlainChabat'), 'Alain Chabat'),
	((SELECT id FROM pers WHERE nom_colle = 'AlexandreAstier'), 'Alexandre Astier'),
	((SELECT id FROM pers WHERE nom_colle = 'AlainDeBitssbailledrey'), 'Alain de Bitssbailledrey'),
	((SELECT id FROM pers WHERE nom_colle = 'ThierryPelouse'), 'Thierry Pelouse'),
	((SELECT id FROM pers WHERE nom_colle = 'AdolfMussolin'), 'Adolf Mussolin'),
	((SELECT id FROM pers WHERE nom_colle = 'GaetanLeSinge'), 'Gaetan Le Singe'),
	((SELECT id FROM pers WHERE nom_colle = 'PacoLopez'), 'Paco Lopez'),
	((SELECT id FROM pers WHERE nom_colle = 'Gims'), 'Gims'),
	((SELECT id FROM pers WHERE nom_colle = 'KevAdams'), 'Kev Adams'),
	((SELECT id FROM pers WHERE nom_colle = 'LeProcureur'), 'le procureur'),
	((SELECT id FROM pers WHERE nom_colle = 'LeProcureur'), 'le procureur de la République'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(JoueurDuGrenier,JDG)}'), 'le Joueur Du Grenier'),
	((SELECT id FROM pers WHERE nom_colle = 'DavidLafarge'), 'David Lafarge'),
	((SELECT id FROM pers WHERE nom_colle = 'CédricVillani'), 'Cédric Villani'),
	((SELECT id FROM pers WHERE nom_colle = 'CédricVillani'), 'C. #Villani'),
	((SELECT id FROM pers WHERE nom_colle = 'Gouvernement'), 'le gouvernement'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(François,)}Asselineau'), 'François Asselineau'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(François,)}Asselineau'), 'F. #Asselineau'),
	((SELECT id FROM pers WHERE nom_colle = 'LoràntDeutsch'), 'Lorànt Deutsch'),
	((SELECT id FROM pers WHERE nom_colle = 'SteveDeMinecraft'), 'Steve de Minecraft'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Laurent,)}Wauquiez'), 'Laurent Wauquiez'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Laurent,)}Wauquiez'), 'L. #Wauquiez'),
	((SELECT id FROM pers WHERE nom_colle = 'AlexisCorbière'), 'Alexis Corbière'),
	((SELECT id FROM pers WHERE nom_colle = 'EdwyPlenel'), 'Edwy Plenel'),
	((SELECT id FROM pers WHERE nom_colle = 'EdwyPlenel'), 'E. #Plenel'),
	((SELECT id FROM pers WHERE nom_colle = 'JeanMichelAulas'), 'Jean-Michel Aulas'),
	((SELECT id FROM pers WHERE nom_colle = 'DidierDeschamps'), 'Didier Deschamps'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Bruno,)}Genesio'), 'Bruno Genesio'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Olivier,)}Giroud'), 'Olivier Giroud'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Florian,)}Thauvin'), 'Florian Thauvin'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Blaise,)}Matuidi'), 'Blaise Matuidi'),
	((SELECT id FROM pers WHERE nom_colle = 'BillDuBigdil'), 'Bill du Bigdil'),
	((SELECT id FROM pers WHERE nom_colle = 'PabloIglesias'), 'Pablo Iglesias'),
	((SELECT id FROM pers WHERE nom_colle = 'GiletJaune'), 'un gilet jaune'),
	((SELECT id FROM pers WHERE nom_colle = 'Thanos'), 'Thanos'),
	((SELECT id FROM pers WHERE nom_colle = 'InventeurDuDab'), 'l’inventeur du dab'),
	((SELECT id FROM pers WHERE nom_colle = '{inventeur_dab.nom_colle}'), 'l’inventeur du dab {inventeur_dab=pers(M)}{inventeur_dab.nom(0)}'),
	((SELECT id FROM pers WHERE nom_colle = 'AdministrateurDeLaPageGiletsJaunes'), 'l’administrateur de la page Gilets Jaunes {rand(15,17,18,19,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83)}'),
	((SELECT id FROM pers WHERE nom_colle = 'AdministrateurDeLaPageGiletsJaunes'), 'l’administrateur de la page Gilets Jaunes {loc_gj=localite(ville,region)}{loc_gj.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'AdministrateurDeLaPageGiletsJaunes'), 'l’administrateur de la page Gilets Jaunes {loc_gj=localite(ville)}{loc_gj.nom(de)} ({loc_gj.departement})'),
	((SELECT id FROM pers WHERE nom_colle = 'BernieSanders'), 'Bernie Sanders'),
	((SELECT id FROM pers WHERE nom_colle = 'JeanPierrePernault'), 'Jean-Pierre Pernault'),
	((SELECT id FROM pers WHERE nom_colle = 'JeanPierrePernault'), 'J.-P. #Pernault'),
	((SELECT id FROM pers WHERE nom_colle = 'FlorianOnAir'), 'FlorianOnAir'),
	((SELECT id FROM pers WHERE nom_colle = 'TiboInShape'), 'Tibo InShape'),
	((SELECT id FROM pers WHERE nom_colle = 'AlainSoral'), 'Alain Soral'),
	((SELECT id FROM pers WHERE nom_colle = 'Dieudonné'), 'Dieudonné'),
	((SELECT id FROM pers WHERE nom_colle = 'PhilippePoutou'), 'Philippe Poutou'),
	((SELECT id FROM pers WHERE nom_colle = 'PhilippePoutou'), 'P. #Poutou'),
	((SELECT id FROM pers WHERE nom_colle = 'OlivierBesancenot'), 'Olivier Besancenot'),
	((SELECT id FROM pers WHERE nom_colle = 'OlivierBesancenot'), 'O. #Besancenot'),
	((SELECT id FROM pers WHERE nom_colle = 'KarimDebbache'), 'Karim Debbache'),
	((SELECT id FROM pers WHERE nom_colle = 'KarimBenzema'), 'Karim Benzema'),
	((SELECT id FROM pers WHERE nom_colle = 'KarimBenzema'), 'K. #Benzema'),
	((SELECT id FROM pers WHERE nom_colle = 'XiJinping'), 'Xi Jinping'),
	((SELECT id FROM pers WHERE nom_colle = 'Journaliste'), 'un journaliste {media.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'Assassin{victime.nom_colle(De)}'), 'l’homme qui a tué {victime=pers}{victime.nom}'),
	((SELECT id FROM pers WHERE nom_colle = 'Victime{assassin.nom_colle(De)}'), 'l’homme qui a été tué par {assassin=pers}{assassin.nom}'),
	((SELECT id FROM pers WHERE nom_colle = 'Avocat{client.nom_colle(De)}'), 'l’avocat {client=pers}{client.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'Agriculteur'), 'un agriculteur'),
	((SELECT id FROM pers WHERE nom_colle = 'Agriculteur'), 'un agriculteur {localite(region).nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'BlackBloc'), 'un membre des blacks blocs'),
	((SELECT id FROM pers WHERE nom_colle = 'CarlosGhosn'), 'Carlos Ghosn'),
	((SELECT id FROM pers WHERE nom_colle = 'PatrickSébastien'), 'Patrick Sébastien'),
	((SELECT id FROM pers WHERE nom_colle = 'JulienLepers'), 'Julien Lepers'),
	((SELECT id FROM pers WHERE nom_colle = 'YannBarthès'), 'Yann Barthès'),
	((SELECT id FROM pers WHERE nom_colle = 'Kirby'), 'Kirby'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Nicolas,)}DupontAignan'), 'Nicolas Dupont-Aignan'),
	((SELECT id FROM pers WHERE nom_colle = 'QuelquUn'), 'quelqu’un'),
	((SELECT id FROM pers WHERE nom_colle = 'Personne'), 'personne'),
	((SELECT id FROM pers WHERE nom_colle = 'Fan{idole.nom_colle(De)}'), 'un fan {idole=pers}{idole.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'StéphanePlaza'), 'Stéphane Plaza'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(JeanClaudeVanDamme,JCVD)}'), 'Jean-Claude Van Damme'),
	((SELECT id FROM pers WHERE nom_colle = 'IbraTV'), 'IbraTV'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Antoine,)}Griezmann'), 'Antoine Griezmann'),
	((SELECT id FROM pers WHERE nom_colle = 'Lacrim'), 'Lacrim'),
	((SELECT id FROM pers WHERE nom_colle = 'Indépendantiste'), 'un indépendantiste {localite(region, pays).adjm}'),
	((SELECT id FROM pers WHERE nom_colle = 'DamienSaez'), 'Damien Saez'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Jérôme,)}Cahuzac'), 'Jérôme Cahuzac'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(François,)}Ruffin'), 'François Ruffin'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(François,)}Ruffin'), 'F. #Ruffin'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(GeorgeW,)}Bush'), 'George W. Bush'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(GeorgeW,)}Bush'), 'George W. #Bush'),
	((SELECT id FROM pers WHERE nom_colle = 'ÉricJudor'), 'Éric Judor'),
	((SELECT id FROM pers WHERE nom_colle = 'BenjaminNetanyahu'), 'Benjamin Netanyahu'),
	((SELECT id FROM pers WHERE nom_colle = 'FilsCaché{parent.nom_colle(De)}'), 'le fils caché {parent=pers}{parent.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'FilsCaché{parent.nom_colle(De)}'), 'l’enfant caché {parent=pers}{parent.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'Terroriste'), 'un terroriste indépendantiste {localite(region,pays).adjm}'),
	((SELECT id FROM pers WHERE nom_colle = 'Terroriste'), 'un terroriste d’extrême-centre'),
	((SELECT id FROM pers WHERE nom_colle = 'Terroriste'), 'un terroriste de centre-gauche'),
	((SELECT id FROM pers WHERE nom_colle = 'Terroriste'), 'un terroriste de la droite modérée'),
	((SELECT id FROM pers WHERE nom_colle = 'Terroriste'), 'un terroriste écologique'),
	((SELECT id FROM pers WHERE nom_colle = 'Terroriste'), 'un terroriste anarchiste'),
	((SELECT id FROM pers WHERE nom_colle = 'JulienCoupat'), 'Julien Coupat'),
	((SELECT id FROM pers WHERE nom_colle = 'Rohff'), 'Rohff'),
	((SELECT id FROM pers WHERE nom_colle = 'Bouteflika'), 'Abdelaziz Bouteflika'),
	((SELECT id FROM pers WHERE nom_colle = 'Bouteflika'), 'A. #Bouteflika'),
	((SELECT id FROM pers WHERE nom_colle = 'Bouteflika'), 'Bouteflika'),
	((SELECT id FROM pers WHERE nom_colle = 'Garfield'), 'Garfield'),
	((SELECT id FROM pers WHERE nom_colle = 'JeanPierreFoucault'), 'Jean-Pierre Foucault'),
	((SELECT id FROM pers WHERE nom_colle = 'DavidGuetta'), 'David Guetta'),
	((SELECT id FROM pers WHERE nom_colle = 'Jack'), 'le PDG de Twitter'),
	((SELECT id FROM pers WHERE nom_colle = 'Jack'), 'le PDG de Twitter Jack Dorsey'),
	((SELECT id FROM pers WHERE nom_colle = 'Jack'), 'Jack Dorsey'),
	((SELECT id FROM pers WHERE nom_colle = 'BenoîtHamon'), 'Benoit Hamon'),
	((SELECT id FROM pers WHERE nom_colle = 'Militant{parti_militant.sigle}'), 'un militant {parti_militant=parti}{parti_militant.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'Militant{parti_militant.sigle}'), 'un militant {parti_militant=parti}{parti_militant.adjm}'),
	((SELECT id FROM pers WHERE nom_colle = 'Militant{parti_militant.sigle}'), 'un {parti_militant=parti}{parti_militant.adjm}'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Jeremy,)}Corbyn'), 'Jeremy Corbyn'),
	((SELECT id FROM pers WHERE nom_colle = 'CRS'), 'un CRS'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Gérard,)}Depardieu'), 'Gérard Depardieu'),
	((SELECT id FROM pers WHERE nom_colle = 'Zizek'), 'Zizek'),
	((SELECT id FROM pers WHERE nom_colle = 'Zizek'), 'Slavoj Žižek'),
	((SELECT id FROM pers WHERE nom_colle = 'Zizek'), 'Slavoj Zizek'),
	((SELECT id FROM pers WHERE nom_colle = 'PewDiePie'), 'PewDiePie'),
	((SELECT id FROM pers WHERE nom_colle = 'Internet'), 'Internet'),
	((SELECT id FROM pers WHERE nom_colle = 'Internet'), 'l’internet'),
	((SELECT id FROM pers WHERE nom_colle = 'YannMoix'), 'Yann Moix'),
	((SELECT id FROM pers WHERE nom_colle = 'Plantu'), 'Plantu'),
	((SELECT id FROM pers WHERE nom_colle = 'AlainTeub'), 'Alain Teub'),
	((SELECT id FROM pers WHERE nom_colle = 'BakariKonté'), 'Bakari Konté'),
	((SELECT id FROM pers WHERE nom_colle = 'DimitriCrackers'), 'Dimitri Crackers'),
	((SELECT id FROM pers WHERE nom_colle = 'JayZ'), 'Jay-Z'),
	((SELECT id FROM pers WHERE nom_colle = 'Maduro'), 'Nicolás Maduro'),
	((SELECT id FROM pers WHERE nom_colle = 'Maduro'), 'Maduro'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Éric,)}DupontMoretti'), 'Éric Dupont-Moretti'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Éric,)}DupontMoretti'), 'E. #DupontMoretti'),
	((SELECT id FROM pers WHERE nom_colle = 'UnHomme'), 'un homme'),
	((SELECT id FROM pers WHERE nom_colle = 'Reggie{rand(Fils-Aimé,)}'), 'Reggie Fils-Aimé'),
	((SELECT id FROM pers WHERE nom_colle = 'AntoineDaniel'), 'Antoine Daniel'),
	((SELECT id FROM pers WHERE nom_colle = 'Drake'), 'Drake'),
	((SELECT id FROM pers WHERE nom_colle = 'ElPueblo'), 'El Pueblo'),
	((SELECT id FROM pers WHERE nom_colle = 'GadElmaleh'), 'Gad Elmaleh'),
	((SELECT id FROM pers WHERE nom_colle = 'PhilippeEtchebest'), 'Philippe Etchebest'),
	((SELECT id FROM pers WHERE nom_colle = 'GordonRamsay'), 'Gordon Ramsay'),
	((SELECT id FROM pers WHERE nom_colle = 'ThomasCyrix'), 'Thomas Cyrix'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(François,)}DeRugy'), 'François De Rugy'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(François,)}DeRugy'), 'F. #DeRugy'),
	((SELECT id FROM pers WHERE nom_colle = 'BorisJohnson'), 'Boris Johnson'),
	((SELECT id FROM pers WHERE nom_colle = 'Maire{ville_maire.nom_colle(De)}'), 'le Maire {ville_maire=localite(ville)}{ville_maire.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'Maire{ville_maire.nom_colle(De)}'), 'le Maire {ville_maire=localite(ville)}{ville_maire.nom(de)} ({ville_maire.departement})'),
	((SELECT id FROM pers WHERE nom_colle = 'FranckyVincent'), 'Francky Vincent'),
	((SELECT id FROM pers WHERE nom_colle = '6ix9ine'), '6ix9ine'),
	((SELECT id FROM pers WHERE nom_colle = 'JeanMarieBigard'), 'Jean-Marie Bigard'),
	((SELECT id FROM pers WHERE nom_colle = 'LaurentAlexandre'), 'Laurent Alexandre'),
	((SELECT id FROM pers WHERE nom_colle = 'LaFilleQuiLitCeci'), 'la fille qui lit ceci'),
	((SELECT id FROM pers WHERE nom_colle = 'BrigitteMacron'), 'Brigitte Macron'),
	((SELECT id FROM pers WHERE nom_colle = 'Bowsette'), 'Bowsette'),
	((SELECT id FROM pers WHERE nom_colle = 'Peach'), 'Peach'),
	((SELECT id FROM pers WHERE nom_colle = 'MarieDAnimalCrossing'), 'Marie d’Animal Crossing'),
	((SELECT id FROM pers WHERE nom_colle = 'MarineLePen'), 'Marine Le Pen'),
	((SELECT id FROM pers WHERE nom_colle = 'MarineLePen'), 'M. #LePen'),
	((SELECT id FROM pers WHERE nom_colle = 'Alexa'), 'Alexa'),
	((SELECT id FROM pers WHERE nom_colle = 'HillaryClinton'), 'Hillary Clinton'),
	((SELECT id FROM pers WHERE nom_colle = 'AdministratriceDeLaPageGiletsJaunes'), 'l’administratrice de la page Gilets Jaunes {rand(15,17,18,19,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83)}'),
	((SELECT id FROM pers WHERE nom_colle = 'AdministratriceDeLaPageGiletsJaunes'), 'l’administratrice de la page Gilets Jaunes {loc_gj=localite(ville,region)}{loc_gj.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'AdministratriceDeLaPageGiletsJaunes'), 'l’administratrice de la page Gilets Jaunes {loc_gj=localite(ville)}{loc_gj.nom(de)} ({loc_gj.departement})'),
	((SELECT id FROM pers WHERE nom_colle = 'Poule'), 'une polue'),
	((SELECT id FROM pers WHERE nom_colle = 'Natoo'), 'Natoo'),
	((SELECT id FROM pers WHERE nom_colle = 'Natoo'), 'Nathalie Odzierejko'),
	((SELECT id FROM pers WHERE nom_colle = 'MylèneFarmer'), 'Mylène Farmer'),
	((SELECT id FROM pers WHERE nom_colle = 'Arielle Dombasle'), 'Arielle Dombasle'),
	((SELECT id FROM pers WHERE nom_colle = 'LaurenceBoccolini'), 'Laurence Boccolini'),
	((SELECT id FROM pers WHERE nom_colle = 'ValérieDamidot'), 'Valérie Damidot'),
	((SELECT id FROM pers WHERE nom_colle = 'AuroreBergé'), 'Aurore Bergé'),
	((SELECT id FROM pers WHERE nom_colle = 'NicoleBelloubet'), 'Nicole Belloubet'),
	((SELECT id FROM pers WHERE nom_colle = 'ChristineBoutin'), 'Christine Boutin'),
	((SELECT id FROM pers WHERE nom_colle = 'FrigideBarjot'), 'Frigide Barjot'),
	((SELECT id FROM pers WHERE nom_colle = 'TheresaMay'), 'Theresa May'),
	((SELECT id FROM pers WHERE nom_colle = 'AyaNakamura'), 'Aya Nakamura'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Angela,)}Merkel'), 'Angela Merkel'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(Angela,)}Merkel'), 'A. #Merkel'),
	((SELECT id FROM pers WHERE nom_colle = 'IsabelleBalkany'), 'Isabelle Balkany'),
	((SELECT id FROM pers WHERE nom_colle = 'Journaliste{ignore(F)}'), 'une journaliste {media.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'Nabilla'), 'Nabilla'),
	((SELECT id FROM pers WHERE nom_colle = 'Nabilla'), 'Nabilla Benattia'),
	((SELECT id FROM pers WHERE nom_colle = 'AnneHidalgo'), 'Anne Hidalgo'),
	((SELECT id FROM pers WHERE nom_colle = 'MelaniaTrump'), 'Melania Trump'),
	((SELECT id FROM pers WHERE nom_colle = 'ÉlisabethII'), 'Élisabeth II'),
	((SELECT id FROM pers WHERE nom_colle = 'ÉlisabethII'), 'la Reine du Royaume-Uni'),
	((SELECT id FROM pers WHERE nom_colle = 'ÉlisabethII'), 'la Reine Élisabeth'),
		((SELECT id FROM pers WHERE nom_colle = 'Agricultrice'), 'une agricultrice'),
	((SELECT id FROM pers WHERE nom_colle = 'Agricultrice'), 'une agricultrice {localite(region).nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'Gendarme'), 'une gendarme'),
	((SELECT id FROM pers WHERE nom_colle = 'ÉliseLucet'), 'Élise Lucet'),
	((SELECT id FROM pers WHERE nom_colle = 'EugénieBastié'), 'Eugénie Bastié'),
	((SELECT id FROM pers WHERE nom_colle = 'ChristineAndTheQueens'), 'Christine and the Queens'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(JK,)}Rowling'), 'J. K. Rowling'),
	((SELECT id FROM pers WHERE nom_colle = '{rand(JK,)}Rowling'), 'J. K. #Rowling'),
	((SELECT id FROM pers WHERE nom_colle = 'BrigitteBardot'), 'Brigitte Bardot'),
	((SELECT id FROM pers WHERE nom_colle = 'SolangeTeParle'), 'Solange Te Parle'),
	((SELECT id FROM pers WHERE nom_colle = 'EnjoyPhoenix'), 'EnjoyPhoenix'),
	((SELECT id FROM pers WHERE nom_colle = 'EnjoyPhoenix'), 'Marie Lopez'),
	((SELECT id FROM pers WHERE nom_colle = 'AzealiaBanks'), 'Azealia Banks'),
	((SELECT id FROM pers WHERE nom_colle = 'Militante{parti_militante.sigle}'), 'une militante {parti_militante=parti}{parti_militante.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'Militante{parti_militante.sigle}'), 'une militante {parti_militante=parti}{parti_militante.adjf}'),
	((SELECT id FROM pers WHERE nom_colle = 'Militante{parti_militante.sigle}'), 'une {parti_militante=parti}{parti_militante.adjf}'),
	((SELECT id FROM pers WHERE nom_colle = 'KimKardashian'), 'Kim Kardashian'),
	((SELECT id FROM pers WHERE nom_colle = 'MarlèneSchiappa'), 'Marlène Schiappa'),
	((SELECT id FROM pers WHERE nom_colle = 'CristinaCordula'), 'Cristina Cordula'),
	((SELECT id FROM pers WHERE nom_colle = 'ValériePécresse'), 'Valérie Pécresse'),
	((SELECT id FROM pers WHERE nom_colle = 'Beyoncé'), 'Beyoncé'),
	((SELECT id FROM pers WHERE nom_colle = 'NickiMinaj'), 'Nicki Minaj'),
	((SELECT id FROM pers WHERE nom_colle = 'Maire{ville_maire.nom_colle(De)}{ignore(F)}'), 'la Maire {ville_maire=localite(ville)}{ville_maire.nom(de)}'),
	((SELECT id FROM pers WHERE nom_colle = 'Maire{ville_maire.nom_colle(De)}{ignore(F)}'), 'la Maire {ville_maire=localite(ville)}{ville_maire.nom(de)} ({ville_maire.departement})'),
	((SELECT id FROM pers WHERE nom_colle = 'GretaThunberg'), 'Greta Thunberg'),
	((SELECT id FROM pers WHERE nom_colle = 'FlashNewsBot'), 'notre rédactrice en chef');
